spring.application.name=com.blogging.app
spring.datasource.url=jdbc:postgresql://localhost:5432/blogging_app
spring.datasource.username=postgres
spring.datasource.password=jermecyrus10
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format-sql=true
spring.jpa.show-sql=true